spring:
  datasource:
    url: #someurl
    username: #username
    password: #passs
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      org.springframework.boot.autoconfigure: DEBUG
      com.example.bookreview: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.thymeleaf: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

